In [13]:
import numpy as np

In [14]:
def vector_outer_multiplication(v1, v2):
    """
    v1, v2: 3d vectors
    return: 3x3 matrix
    """
    return np.array([[v1[0]*v2[0], v1[0]*v2[1], v1[0]*v2[2]],
                     [v1[1]*v2[0], v1[1]*v2[1], v1[1]*v2[2]],
                     [v1[2]*v2[0], v1[2]*v2[1], v1[2]*v2[2]]])

In [15]:
# 4x4 matrix
def convert_to_quartenion_matrix(K):
    """
    K: 3x3 matrix
    return: 4x4 matrix
    """
    K_hat = np.array([
        [K[0,0]+K[1,1]+K[2,2], K[2,1]-K[1,2], K[0,2]-K[2,0], K[1,0]-K[0,1]],
        [K[2,1]-K[1,2], K[0,0]-K[1,1]-K[2,2], K[0,1]+K[1,0], K[2,0]+K[0,2]],
        [K[0,2]-K[2,0], K[0,1]+K[1,0], -K[0,0]+K[1,1]-K[2,2], K[1,2]+K[2,1]],
        [K[1,0]-K[0,1], K[2,0]+K[0,2], K[1,2]+K[2,1], -K[0,0]-K[1,1]+K[2,2]],
    ])
    
    return K_hat

In [16]:
from numpy import linalg as LA

# Eigen values and vectors
def eigen_values_and_vectors(K):
    """
    K: 3x3 matrix
    return: eigen values and vectors
    """
    e_values, e_vectors = LA.eig(K)

    E_Vectors = np.array([x for _,x in sorted(zip(e_values,e_vectors.T),reverse=True)]).T
    E_Values = np.array(sorted(e_values,reverse=True))
    
    return E_Values, E_Vectors

In [17]:
class Vector():
    def __init__(self, x, y, f=None):
        self.x = x
        self.y = y
        self.f = f

        self.f = 6420
        self.x_correction = 2000
        self.y_correction = 1125
    
    def get_vector(self):
        return np.array([self.x - self.x_correction, self.y_correction - self.y, self.f])


In [18]:
def normalise_vector(v):
    return v / LA.norm(v)

In [19]:
first_p1 = Vector(1204, 860, )
first_p2 = Vector(1208, 2056, )
first_p3 = Vector(1640, 476, )
first_p4 = Vector(304, 1204, )
first_p5 = Vector(1496, 2064, )
first_p6 = Vector(2540, 872, )
first_p7 = Vector(300, 1464, )
first_p8 = Vector(332, 1552, )

second_p1 = Vector(1764, 912, )
second_p2 = Vector(1748, 2096, )
second_p3 = Vector(2176, 528, )
second_p4 = Vector(940, 1244, )
second_p5 = Vector(2036, 2112, )
second_p6 = Vector(3156, 912, )
second_p7 = Vector(940, 1480, )
second_p8 = Vector(948, 1560, )

In [20]:
# Vectors
first_vectors = [
    first_p1.get_vector(),
    first_p2.get_vector(),
    first_p3.get_vector(),
    first_p4.get_vector(),
    first_p5.get_vector(),
    first_p6.get_vector(),
    first_p7.get_vector(),
    first_p8.get_vector(),
]

second_vectors = [
    second_p1.get_vector(),
    second_p2.get_vector(),
    second_p3.get_vector(),
    second_p4.get_vector(),
    second_p5.get_vector(),
    second_p6.get_vector(),
    second_p7.get_vector(),
    second_p8.get_vector(),
]

# Normalise vectors
for i in range(len(first_vectors)):
    first_vectors[i] = normalise_vector(first_vectors[i])
    second_vectors[i] = normalise_vector(second_vectors[i])

In [21]:
# Calculate K
K = np.zeros((3,3))
for i in range(len(first_vectors)):
    K += vector_outer_multiplication(first_vectors[i], second_vectors[i])
    
K_hat = convert_to_quartenion_matrix(K)
E_Values, E_Vectors = eigen_values_and_vectors(K_hat)

print("K_hat: \n", K_hat)
print("E_Values: \n", E_Values)
print("E_Vectors: \n", E_Vectors)

K_hat: 
 [[ 7.96817446 -0.04496713 -0.70710645 -0.02521204]
 [-0.04496713 -7.67663782  0.09222648 -1.37892725]
 [-0.70710645  0.09222648 -7.84332584 -0.50324812]
 [-0.02521204 -1.37892725 -0.50324812  7.5517892 ]]
E_Values: 
 [ 7.99989536  7.69233695 -7.78237476 -7.90985755]
E_Vectors: 
 [[-0.99897815 -0.00682891  0.01974449  0.04007716]
 [ 0.003575   -0.08948678  0.92074323 -0.37975154]
 [ 0.04476779 -0.03246564  0.37785326  0.9242125 ]
 [-0.00507175  0.99543531  0.09523112 -0.00372089]]


In [22]:
first_p1 = Vector(1764, 908, )
first_p2 = Vector(1752, 2096, )
first_p3 = Vector(3156, 912, )
first_p4 = Vector(3100, 452, )
first_p5 = Vector(2184, 508, )
first_p6 = Vector(360, 1020, )
first_p7 = Vector(444, 1520, )
first_p8 = Vector(2368, 376, )

second_p1 = Vector(2248, 936, )  
second_p2 = Vector(2240, 2116, )
second_p3 = Vector(3764, 924, )
second_p4 = Vector(3716, 428, )
second_p5 = Vector(2700, 532, )
second_p6 = Vector(980, 1048, )
second_p7 = Vector(1052, 1508, )
second_p8 = Vector(2896, 376, )

In [23]:
# Vectors
first_vectors = [
    first_p1.get_vector(),
    first_p2.get_vector(),
    first_p3.get_vector(),
    first_p4.get_vector(),
    first_p5.get_vector(),
    first_p6.get_vector(),
    first_p7.get_vector(),
    first_p8.get_vector(),
]

second_vectors = [
    second_p1.get_vector(),
    second_p2.get_vector(),
    second_p3.get_vector(),
    second_p4.get_vector(),
    second_p5.get_vector(),
    second_p6.get_vector(),
    second_p7.get_vector(),
    second_p8.get_vector(),
]

# Normalise vectors
for i in range(len(first_vectors)):
    first_vectors[i] = normalise_vector(first_vectors[i])
    second_vectors[i] = normalise_vector(second_vectors[i])

In [24]:
# Calculate K
K = np.zeros((3,3))
for i in range(len(first_vectors)):
    K += vector_outer_multiplication(first_vectors[i], second_vectors[i])
    
K_hat = convert_to_quartenion_matrix(K)
E_Values, E_Vectors = eigen_values_and_vectors(K_hat)

print("K_hat: \n", K_hat)
print("E_Values: \n", E_Values)
print("E_Vectors: \n", E_Vectors)

K_hat: 
 [[ 7.97127775 -0.0117053  -0.67208237  0.01558802]
 [-0.0117053  -7.62883755  0.11090831  0.40270275]
 [-0.67208237  0.11090831 -7.8488623   0.35134753]
 [ 0.01558802  0.40270275  0.35134753  7.5064221 ]]
E_Values: 
 [ 7.99979563  7.52528845 -7.6034674  -7.92161667]
E_Vectors: 
 [[-9.99101590e-01  4.49564061e-04  1.52561124e-02  3.95355652e-02]
 [ 1.03465409e-03  2.67253388e-02  9.41023518e-01 -3.37282412e-01]
 [ 4.23631313e-02  2.30120575e-02  3.36390288e-01  9.40487844e-01]
 [-5.53698635e-04  9.99377806e-01 -3.29175447e-02 -1.26542208e-02]]
